In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Cleaned Dataset.csv')

In [3]:
df.head()

State  Year      Season          Crop   Area  \
0  Andaman and Nicobar Islands  2000      Kharif          Rice  102.0   
1  Andaman and Nicobar Islands  2000  Whole Year        Banana  176.0   
2  Andaman and Nicobar Islands  2000  Whole Year    Dry ginger   36.0   
3  Andaman and Nicobar Islands  2000  Whole Year     Sugarcane    1.0   
4  Andaman and Nicobar Islands  2000  Whole Year  Sweet potato    5.0   

   Rainfall  Production  
0    2763.2       321.0  
1    2763.2       641.0  
2    2763.2       100.0  
3    2763.2         2.0  
4    2763.2        15.0

In [4]:
df.shape

(64360, 7)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64360 entries, 0 to 64359
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   State       64360 non-null  object 
 1   Year        64360 non-null  int64  
 2   Season      64360 non-null  object 
 3   Crop        64360 non-null  object 
 4   Area        64360 non-null  float64
 5   Rainfall    64360 non-null  float64
 6   Production  64360 non-null  float64
dtypes: float64(3), int64(1), object(3)
memory usage: 3.4+ MB


In [6]:
df.corr()

Year      Area  Rainfall  Production
Year        1.000000  0.000101 -0.017956   -0.018868
Area        0.000101  1.000000 -0.110295    0.241445
Rainfall   -0.017956 -0.110295  1.000000   -0.065504
Production -0.018868  0.241445 -0.065504    1.000000

In [7]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1].values

### One Hot Encoding

#### We are Applying to the Categorical Values present in the X (Features)

In [8]:
categorical_data = ['State', 'Season', 'Crop']

for label in categorical_data:
    print(label ,': ', len(df[label].unique()))

State :  12
Season :  3
Crop :  33


In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('encoder', OneHotEncoder(sparse=False, drop="first"), [0,2,3])], remainder = 'passthrough')

In [10]:
X = ct.fit_transform(X)

In [11]:
print(X)

[[0.0000e+00 0.0000e+00 0.0000e+00 ... 2.0000e+03 1.0200e+02 2.7632e+03]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 2.0000e+03 1.7600e+02 2.7632e+03]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 2.0000e+03 3.6000e+01 2.7632e+03]
 ...
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 2.0140e+03 2.6000e+01 1.2874e+03]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 2.0140e+03 9.9190e+03 1.2874e+03]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 2.0140e+03 3.0000e+00 1.2874e+03]]


In [12]:
dummy_df = pd.get_dummies(df, drop_first= True)

In [13]:
dummy_df.keys()

Index(['Year', 'Area', 'Rainfall', 'Production', 'State_Arunachal Pradesh',
       'State_Bihar', 'State_Chhattisgarh', 'State_Himachal Pradesh',
       'State_Jammu and Kashmir', 'State_Jharkhand', 'State_Kerala',
       'State_Odisha', 'State_Punjab', 'State_Tamil Nadu', 'State_Uttarakhand',
       'Season_Rabi', 'Season_Whole Year', 'Crop_Bajra', 'Crop_Banana',
       'Crop_Barley', 'Crop_Castor seed', 'Crop_Coriander',
       'Crop_Cotton(lint)', 'Crop_Dry chillies', 'Crop_Dry ginger',
       'Crop_Garlic', 'Crop_Gram', 'Crop_Groundnut', 'Crop_Horse-gram',
       'Crop_Jowar', 'Crop_Khesari', 'Crop_Linseed', 'Crop_Maize',
       'Crop_Masoor', 'Crop_Moong(Green Gram)', 'Crop_Onion',
       'Crop_Peas & beans (Pulses)', 'Crop_Potato', 'Crop_Ragi',
       'Crop_Rapeseed &Mustard', 'Crop_Rice', 'Crop_Sesamum',
       'Crop_Small millets', 'Crop_Sugarcane', 'Crop_Sunflower',
       'Crop_Sweet potato', 'Crop_Turmeric', 'Crop_Urad', 'Crop_Wheat'],
      dtype='object')

In [14]:
oh_enc_df = pd.DataFrame(X, columns=['Arunachal Pradesh',
       'Bihar', 'Chhattisgarh', 'Himachal Pradesh',
       'Jammu and Kashmir', 'Jharkhand', 'Kerala',
       'Odisha', 'Punjab', 'Tamil Nadu', 'Uttarakhand',
       'Rabi', 'Whole Year', 'Bajra', 'Banana',
       'Barley', 'Castor seed', 'Coriander',
       'Cotton', 'Dry chillies', 'Dry ginger',
       'Garlic', 'Gram', 'Groundnut', 'Horse-gram',
       'Jowar', 'Khesari', 'Linseed', 'Maize',
       'Masoor', 'Moong(Green Gram)', 'Onion',
       'Peas & beans (Pulses)', 'Potato', 'Ragi',
       'Rapeseed &Mustard', 'Rice', 'Sesamum',
       'Small millets', 'Sugarcane', 'Sunflower',
       'Sweet potato', 'Turmeric', 'Urad', 'Wheat','Year', 'Area', 'Rainfall'])

oh_enc_df.head()

Arunachal Pradesh  Bihar  Chhattisgarh  Himachal Pradesh  \
0                0.0    0.0           0.0               0.0   
1                0.0    0.0           0.0               0.0   
2                0.0    0.0           0.0               0.0   
3                0.0    0.0           0.0               0.0   
4                0.0    0.0           0.0               0.0   

   Jammu and Kashmir  Jharkhand  Kerala  Odisha  Punjab  Tamil Nadu  ...  \
0                0.0        0.0     0.0     0.0     0.0         0.0  ...   
1                0.0        0.0     0.0     0.0     0.0         0.0  ...   
2                0.0        0.0     0.0     0.0     0.0         0.0  ...   
3                0.0        0.0     0.0     0.0     0.0         0.0  ...   
4                0.0        0.0     0.0     0.0     0.0         0.0  ...   

   Small millets  Sugarcane  Sunflower  Sweet potato  Turmeric  Urad  Wheat  \
0            0.0        0.0        0.0           0.0       0.0   0.0    0.0   
1            0.0        0.0        0.0           0.0       0.0   0.0    0.0   
2            0.0        0.0        0.0           0.0       0.0   0.0    0.0   
3            0.0        1.0        0.0           0.0       0.0   0.0    0.0   
4            0.0        0.0        0.0           1.0       0.0   0.0    0.0   

     Year   Area  Rainfall  
0  2000.0  102.0    2763.2  
1  2000.0  176.0    2763.2  
2  2000.0   36.0    2763.2  
3  2000.0    1.0    2763.2  
4  2000.0    5.0    2763.2  

[5 rows x 48 columns]

In [15]:
neworder = ['Year', 'Area', 'Rainfall','Arunachal Pradesh', 'Bihar', 'Chhattisgarh', 'Himachal Pradesh',
       'Jammu and Kashmir', 'Jharkhand', 'Kerala', 'Odisha', 'Punjab',
       'Tamil Nadu', 'Uttarakhand', 'Rabi', 'Whole Year', 'Bajra', 'Banana',
       'Barley', 'Castor seed', 'Coriander', 'Cotton', 'Dry chillies',
       'Dry ginger', 'Garlic', 'Gram', 'Groundnut', 'Horse-gram', 'Jowar',
       'Khesari', 'Linseed', 'Maize', 'Masoor', 'Moong(Green Gram)', 'Onion',
       'Peas & beans (Pulses)', 'Potato', 'Ragi', 'Rapeseed &Mustard', 'Rice',
       'Sesamum', 'Small millets', 'Sugarcane', 'Sunflower', 'Sweet potato',
       'Turmeric', 'Urad', 'Wheat']

oh_enc_df = oh_enc_df[neworder]

In [16]:
oh_enc_df.head()

Year   Area  Rainfall  Arunachal Pradesh  Bihar  Chhattisgarh  \
0  2000.0  102.0    2763.2                0.0    0.0           0.0   
1  2000.0  176.0    2763.2                0.0    0.0           0.0   
2  2000.0   36.0    2763.2                0.0    0.0           0.0   
3  2000.0    1.0    2763.2                0.0    0.0           0.0   
4  2000.0    5.0    2763.2                0.0    0.0           0.0   

   Himachal Pradesh  Jammu and Kashmir  Jharkhand  Kerala  ...  \
0               0.0                0.0        0.0     0.0  ...   
1               0.0                0.0        0.0     0.0  ...   
2               0.0                0.0        0.0     0.0  ...   
3               0.0                0.0        0.0     0.0  ...   
4               0.0                0.0        0.0     0.0  ...   

   Rapeseed &Mustard  Rice  Sesamum  Small millets  Sugarcane  Sunflower  \
0                0.0   1.0      0.0            0.0        0.0        0.0   
1                0.0   0.0      0.0            0.0        0.0        0.0   
2                0.0   0.0      0.0            0.0        0.0        0.0   
3                0.0   0.0      0.0            0.0        1.0        0.0   
4                0.0   0.0      0.0            0.0        0.0        0.0   

   Sweet potato  Turmeric  Urad  Wheat  
0           0.0       0.0   0.0    0.0  
1           0.0       0.0   0.0    0.0  
2           0.0       0.0   0.0    0.0  
3           0.0       0.0   0.0    0.0  
4           1.0       0.0   0.0    0.0  

[5 rows x 48 columns]

#### Columns : state->11, season->2, Crop->32, Year, Area, Rainfall ||Total ->48

In [17]:
oh_enc_df.shape

(64360, 48)

### Splitting the data

In [18]:
y = y.reshape(len(y),1)

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 42)

### Feature Scaling

In [20]:
# from sklearn.preprocessing import StandardScaler

# sc_X = StandardScaler()
# sc_y = StandardScaler()
# X = sc_X.fit_transform(X)
# y = sc_y.fit_transform(y)

### Random Forest Regressor

In [21]:
from sklearn.ensemble import RandomForestRegressor

regr = RandomForestRegressor(random_state=0, n_estimators=50)
regr.fit(X_train, y_train.ravel())
y_pred = regr.predict(X_test)

from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import r2_score

print('R2 Score =', r2_score(y_pred, y_test)*100)

R2 Score = 87.88591527206793


### Using K-Fold cross validation

In [22]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

cross_val_score(RandomForestRegressor(random_state=0, n_estimators=50), X, y.ravel(), cv=cv)

array([0.94602501, 0.95462166, 0.94671871, 0.91038406, 0.97173345])

### Saving the model

In [23]:
import pickle

with open('crop_yeild_prediction.pickle','wb') as f:
    pickle.dump(regr,f)

### Testing the model

In [24]:
oh_enc_df.head()

Year   Area  Rainfall  Arunachal Pradesh  Bihar  Chhattisgarh  \
0  2000.0  102.0    2763.2                0.0    0.0           0.0   
1  2000.0  176.0    2763.2                0.0    0.0           0.0   
2  2000.0   36.0    2763.2                0.0    0.0           0.0   
3  2000.0    1.0    2763.2                0.0    0.0           0.0   
4  2000.0    5.0    2763.2                0.0    0.0           0.0   

   Himachal Pradesh  Jammu and Kashmir  Jharkhand  Kerala  ...  \
0               0.0                0.0        0.0     0.0  ...   
1               0.0                0.0        0.0     0.0  ...   
2               0.0                0.0        0.0     0.0  ...   
3               0.0                0.0        0.0     0.0  ...   
4               0.0                0.0        0.0     0.0  ...   

   Rapeseed &Mustard  Rice  Sesamum  Small millets  Sugarcane  Sunflower  \
0                0.0   1.0      0.0            0.0        0.0        0.0   
1                0.0   0.0      0.0            0.0        0.0        0.0   
2                0.0   0.0      0.0            0.0        0.0        0.0   
3                0.0   0.0      0.0            0.0        1.0        0.0   
4                0.0   0.0      0.0            0.0        0.0        0.0   

   Sweet potato  Turmeric  Urad  Wheat  
0           0.0       0.0   0.0    0.0  
1           0.0       0.0   0.0    0.0  
2           0.0       0.0   0.0    0.0  
3           0.0       0.0   0.0    0.0  
4           1.0       0.0   0.0    0.0  

[5 rows x 48 columns]

In [25]:
oh_enc_df.columns

Index(['Year', 'Area', 'Rainfall', 'Arunachal Pradesh', 'Bihar',
       'Chhattisgarh', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand',
       'Kerala', 'Odisha', 'Punjab', 'Tamil Nadu', 'Uttarakhand', 'Rabi',
       'Whole Year', 'Bajra', 'Banana', 'Barley', 'Castor seed', 'Coriander',
       'Cotton', 'Dry chillies', 'Dry ginger', 'Garlic', 'Gram', 'Groundnut',
       'Horse-gram', 'Jowar', 'Khesari', 'Linseed', 'Maize', 'Masoor',
       'Moong(Green Gram)', 'Onion', 'Peas & beans (Pulses)', 'Potato', 'Ragi',
       'Rapeseed &Mustard', 'Rice', 'Sesamum', 'Small millets', 'Sugarcane',
       'Sunflower', 'Sweet potato', 'Turmeric', 'Urad', 'Wheat'],
      dtype='object')

In [26]:
np.where(oh_enc_df.columns=='Tamil Nadu')[0][0]

12

In [27]:
np.where(oh_enc_df.columns=='Sugarcane')[0][0]

42

In [28]:
np.where(oh_enc_df.columns=='Rabi')[0][0]

14

In [29]:
def predict_production(state,crop,season,year,area, rainfall):    
    state_index = np.where(oh_enc_df.columns == state)[0][0]
    crop_index = np.where(oh_enc_df.columns == crop)[0][0]
    

    x = np.zeros(len(oh_enc_df.columns))
    x[0] = year 
    x[1] = area 
    x[2] = rainfall

    if state_index >=0:
        x[state_index] = 1
    
    if crop_index >=0:
        x[crop_index] = 1

    seasons = ['Rabi', 'Whole Year']
    if season in seasons:
      season_index = np.where(oh_enc_df.columns == season)[0][0]
      if season_index >=0:
          x[season_index] = 1
    else:
        x[14]=0
        x[15]=0
          
    
    return regr.predict([x])[0]

### Predicting Some results