In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Cleaned Dataset.csv')

In [3]:
df.head()

State  Year      Season          Crop   Area  \
0  Andaman and Nicobar Islands  2000      Kharif          Rice  102.0   
1  Andaman and Nicobar Islands  2000  Whole Year        Banana  176.0   
2  Andaman and Nicobar Islands  2000  Whole Year    Dry ginger   36.0   
3  Andaman and Nicobar Islands  2000  Whole Year     Sugarcane    1.0   
4  Andaman and Nicobar Islands  2000  Whole Year  Sweet potato    5.0   

   Rainfall  Production  
0    2763.2       321.0  
1    2763.2       641.0  
2    2763.2       100.0  
3    2763.2         2.0  
4    2763.2        15.0

In [4]:
df.shape

(64360, 7)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64360 entries, 0 to 64359
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   State       64360 non-null  object 
 1   Year        64360 non-null  int64  
 2   Season      64360 non-null  object 
 3   Crop        64360 non-null  object 
 4   Area        64360 non-null  float64
 5   Rainfall    64360 non-null  float64
 6   Production  64360 non-null  float64
dtypes: float64(3), int64(1), object(3)
memory usage: 3.4+ MB


In [6]:
df.corr()

Year      Area  Rainfall  Production
Year        1.000000  0.000101 -0.017956   -0.018868
Area        0.000101  1.000000 -0.110295    0.241445
Rainfall   -0.017956 -0.110295  1.000000   -0.065504
Production -0.018868  0.241445 -0.065504    1.000000

In [7]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

### One Hot Encoding

#### We are Applying to the Categorical Values present in the X (Features)

In [8]:
categorical_data = ['State', 'Season', 'Crop']

for label in categorical_data:
    print(label ,': ', len(df[label].unique()))

State :  12
Season :  3
Crop :  33


In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ohe =  OneHotEncoder(sparse=False, drop="first")
ct = ColumnTransformer([('encoder', ohe, [0,2,3])], remainder = 'passthrough')

In [10]:
X = ct.fit_transform(X)

In [11]:
print(X)

[[0.0 0.0 0.0 ... 2000 102.0 2763.2]
 [0.0 0.0 0.0 ... 2000 176.0 2763.2]
 [0.0 0.0 0.0 ... 2000 36.0 2763.2]
 ...
 [0.0 0.0 0.0 ... 2014 26.0 1287.4]
 [0.0 0.0 0.0 ... 2014 9919.0 1287.4]
 [0.0 0.0 0.0 ... 2014 3.0 1287.4]]


In [12]:
X_df = pd.DataFrame(X)
X_df.head() # shows that last 3 columns are -> Year, Area and Rainfall

0  1  2  3  4  5  6  7  8  9   ... 38 39 40 41 42 43 44    45   46      47
0  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  2000  102  2763.2
1  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  2000  176  2763.2
2  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  2000   36  2763.2
3  0  0  0  0  0  0  0  0  0  0  ...  0  1  0  0  0  0  0  2000    1  2763.2
4  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  1  0  0  0  2000    5  2763.2

[5 rows x 48 columns]

In [13]:
dummy_df = pd.get_dummies(df, drop_first= True)

In [14]:
dummy_df.keys()

Index(['Year', 'Area', 'Rainfall', 'Production', 'State_Arunachal Pradesh',
       'State_Bihar', 'State_Chhattisgarh', 'State_Himachal Pradesh',
       'State_Jammu and Kashmir', 'State_Jharkhand', 'State_Kerala',
       'State_Odisha', 'State_Punjab', 'State_Tamil Nadu', 'State_Uttarakhand',
       'Season_Rabi', 'Season_Whole Year', 'Crop_Bajra', 'Crop_Banana',
       'Crop_Barley', 'Crop_Castor seed', 'Crop_Coriander',
       'Crop_Cotton(lint)', 'Crop_Dry chillies', 'Crop_Dry ginger',
       'Crop_Garlic', 'Crop_Gram', 'Crop_Groundnut', 'Crop_Horse-gram',
       'Crop_Jowar', 'Crop_Khesari', 'Crop_Linseed', 'Crop_Maize',
       'Crop_Masoor', 'Crop_Moong(Green Gram)', 'Crop_Onion',
       'Crop_Peas & beans (Pulses)', 'Crop_Potato', 'Crop_Ragi',
       'Crop_Rapeseed &Mustard', 'Crop_Rice', 'Crop_Sesamum',
       'Crop_Small millets', 'Crop_Sugarcane', 'Crop_Sunflower',
       'Crop_Sweet potato', 'Crop_Turmeric', 'Crop_Urad', 'Crop_Wheat'],
      dtype='object')

In [15]:
oh_enc_df = pd.DataFrame(X, columns=['Arunachal Pradesh',
       'Bihar', 'Chhattisgarh', 'Himachal Pradesh',
       'Jammu and Kashmir', 'Jharkhand', 'Kerala',
       'Odisha', 'Punjab', 'Tamil Nadu', 'Uttarakhand',
       'Rabi', 'Whole Year', 'Bajra', 'Banana',
       'Barley', 'Castor seed', 'Coriander',
       'Cotton', 'Dry chillies', 'Dry ginger',
       'Garlic', 'Gram', 'Groundnut', 'Horse-gram',
       'Jowar', 'Khesari', 'Linseed', 'Maize',
       'Masoor', 'Moong(Green Gram)', 'Onion',
       'Peas & beans (Pulses)', 'Potato', 'Ragi',
       'Rapeseed &Mustard', 'Rice', 'Sesamum',
       'Small millets', 'Sugarcane', 'Sunflower',
       'Sweet potato', 'Turmeric', 'Urad', 'Wheat','Year', 'Area', 'Rainfall'])

oh_enc_df.head()

Arunachal Pradesh Bihar Chhattisgarh Himachal Pradesh Jammu and Kashmir  \
0                 0     0            0                0                 0   
1                 0     0            0                0                 0   
2                 0     0            0                0                 0   
3                 0     0            0                0                 0   
4                 0     0            0                0                 0   

  Jharkhand Kerala Odisha Punjab Tamil Nadu  ... Small millets Sugarcane  \
0         0      0      0      0          0  ...             0         0   
1         0      0      0      0          0  ...             0         0   
2         0      0      0      0          0  ...             0         0   
3         0      0      0      0          0  ...             0         1   
4         0      0      0      0          0  ...             0         0   

  Sunflower Sweet potato Turmeric Urad Wheat  Year Area Rainfall  
0         0            0        0    0     0  2000  102   2763.2  
1         0            0        0    0     0  2000  176   2763.2  
2         0            0        0    0     0  2000   36   2763.2  
3         0            0        0    0     0  2000    1   2763.2  
4         0            1        0    0     0  2000    5   2763.2  

[5 rows x 48 columns]

#### Columns : state->11, season->2, Crop->32, Year, Area, Rainfall ||Total ->48

In [16]:
oh_enc_df.shape

(64360, 48)

### Splitting the data

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

### Random Forest Regressor

In [18]:
from sklearn.ensemble import RandomForestRegressor

regr = RandomForestRegressor(random_state=0, n_estimators=50)
regr.fit(X_train, y_train.ravel())

RandomForestRegressor(n_estimators=50, random_state=0)

In [19]:
print('R2 Score =', regr.score(X_test, y_test)*100)

R2 Score = 98.06136221540595


### Using K-Fold cross validation

In [20]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

cross_val_score(RandomForestRegressor(random_state=0, n_estimators=50), X, y.ravel(), cv=cv)

array([0.94602501, 0.95462166, 0.94671871, 0.91038406, 0.97173345])

### Saving the model

In [21]:
import pickle

with open('crop_yeild_prediction.pickle','wb') as f:
    pickle.dump(regr,f)

### Testing the model

In [22]:
# these are the records of respective columns present in the X(Features), After OHE
states = ['Arunachal Pradesh','Bihar', 'Chhattisgarh', 'Himachal Pradesh','Jammu and Kashmir', 'Jharkhand', 'Kerala','Odisha', 'Punjab', 'Tamil Nadu', 'Uttarakhand']
seasons = ['Rabi', 'Whole Year']
crops = ['Bajra', 'Banana','Barley', 'Castor seed', 'Coriander','Cotton', 'Dry chillies', 'Dry ginger','Garlic', 'Gram', 'Groundnut', 'Horse-gram','Jowar', 'Khesari', 'Linseed', 'Maize','Masoor', 'Moong(Green Gram)', 'Onion','Peas & beans (Pulses)', 'Potato', 'Ragi','Rapeseed &Mustard', 'Rice', 'Sesamum','Small millets', 'Sugarcane', 'Sunflower','Sweet potato', 'Turmeric', 'Urad', 'Wheat']

In [23]:
# This function is used to take the inpts and display the output (Production)
def predict_production(state,crop,season,year,area, rainfall):      

    x = np.zeros(len(oh_enc_df.columns))
    x[-3] = year 
    x[-2] = area 
    x[-1] = rainfall

    # To overcome dummy variable trap Andaman, Arhar/Tur and Kharif have been removed to overcome that we need this code:
    if state in states:
      state_index = np.where(oh_enc_df.columns == state)[0][0]
      if state_index >=0:
        x[state_index] = 1
    else:
        x[0:11]=0

    if season in seasons:
      season_index = np.where(oh_enc_df.columns == season)[0][0]
      if season_index >=0:
          x[season_index] = 1
    else:
        x[11:13]=0
    
    if crop in crops:
      crop_index = np.where(oh_enc_df.columns == crop)[0][0]
      if crop_index >=0:
          x[crop_index] = 1
    else:
        x[13:45]=0
   
    # print(x.size)
    # print(x.ndim)
    # print(x)

    return regr.predict([x])[0]      

# Predicting Some results





In [24]:
df_bihar_maize = df[(df['State'] == 'Bihar') & (df['Crop']== 'Maize') & (df['Season'] == 'Rabi') & (df['Year'] == 2011) & (df['Area'] == 43626)]

In [25]:
df_bihar_maize.shape

(1, 7)

In [26]:
df_bihar_maize.head(1)

State  Year Season   Crop     Area  Rainfall  Production
14161  Bihar  2011   Rabi  Maize  43626.0    1097.1    154451.0

In [27]:
predict_production('Bihar','Maize','Rabi',2011, 43626 ,1097.1 ) # original -> 154451

139384.02

In [28]:
df_Rice_Chattisgarh = df[(df['State'] == 'Chhattisgarh') & (df['Crop']== 'Rice') & (df['Season'] == 'Kharif') & (df['Year'] == 2011)]

In [29]:
df_Rice_Chattisgarh.head(1)

State  Year  Season  Crop      Area  Rainfall  Production
19144  Chhattisgarh  2011  Kharif  Rice  177115.0    1302.7    327525.0

In [30]:
predict_production('Chhattisgarh','Rice','Kharif',2011 ,177115.0 ,1302.7) #original -> 327525.0

324759.38

In [31]:
df_andaman_banana= df[(df['State'] == 'Andaman and Nicobar Islands') & (df['Crop']== 'Banana') & (df['Season'] == 'Whole Year') & (df['Year'] == 2006)]

In [32]:
df_andaman_banana.head(1)

State  Year      Season    Crop   Area  Rainfall  \
25  Andaman and Nicobar Islands  2006  Whole Year  Banana  198.0    2404.7   

    Production  
25       976.0

In [33]:
predict_production('Andaman and Nicobar Islands','Banana','Whole Year',2006 ,198 ,2404.7) #original -> 976.0

1097.6224

In [34]:
df_arhar= df[(df['State'] == 'Tamil Nadu') & (df['Crop']== 'Arhar/Tur') & (df['Season'] == 'Whole Year') & (df['Year'] == 1997)]


In [35]:
df_arhar.head(1)

State  Year      Season       Crop    Area  Rainfall  Production
50817  Tamil Nadu  1997  Whole Year  Arhar/Tur  1393.0     950.5       700.0

In [36]:
predict_production('Tamil Nadu','Arhar/Tur','Whole Year',1997 ,1393 ,950.5) # original -> 700

885.06